# Site settings
title: Alec Grover
email: alec.grover999@gmail.com
url: https://www.alecgrover.com
description: "Alec Grover's portfolio. It is said that any sufficiently advanced technology is indistinguishable from magic. Let's make some magic."
keywords: "your keywords, separated by commas"
skills: "Software Engineer - Game Developer - World Builder"
meta_author: Grover Alec
about-left: Alec Grover is a Canadian software engineer and game developer. He recently graduated with a degree in Computer Science and is excited to be starting out into the games industry. Alec is very experienced in C# and Unity, and he is currently working with C++ and Unreal to further bolster his development background.
about-right: Games have always been a big part of who I am. From my earliest memories of my cousins handing me a controller while they played Halo CE, to the years spent building and running Minecraft servers, all the way through today, games have profoundly impacted me. I could think of nothing better than making the platforms to inspire the next generation.

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: f7bea9 #80B3FF
  primary-rgb: "239,152,167" #"24,288,156" #"128,179,255"
  secondary: 807094 #736663 #FD6E8A
  secondary-dark: 604f71 #A2122F

# Footer settings
footer:
  copyright: Alec Grover
  location: Surrey, BC
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/SlushOnTTV
  - title: linkedin
    url: https://www.linkedin.com/in/alecgrover/
  - title: itch-io
    url: http://sergeant-slash.itch.io
  - title: github
    url: http://github.com/AlecGrover

# Postal address (add as many lines as necessary)
address:
  - line: 2201 123 Street
  - line: Surrey, BC V4A 3L6
  - line: Canada

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
